# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0  # LTS version
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly
matrix:
  allow_failures:
  - julia: nightly
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # version tags
notifications:
  email: false
after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 1.0 ]]; then
      julia --project -e 'using Pkg; pkg"add Coverage"; using Coverage; Codecov.submit(Codecov.process_folder())';
    fi
jobs:
  include:
    - stage: Documentation
      julia: 1.0
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip
