name: 'JuliaFormatter'

# Based off of https://github.com/julia-actions/julia-format/blob/096371fb8d24867760569a7a89359a677595503b/workflows/format_check.yml

on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  format-check:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.3.0'
      - uses: actions/checkout@v2
      - name: 'run format.sh (installs pinned version of JuliaFormatter and runs `format` on all files)'
        run: ./scripts/format.sh
      - name: 'Check that running `format` is a no-op.'
        run: |
          julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files did not meet the formatting guidelines. Run ./scripts/format.sh to fix."
              write(stdout, "\nFiles not meeting formatting guidelines:\n")
              write(stdout, out)
              write(stdout, "\nRun ./scripts/format.sh to fix.")
              exit(1)
          end'
