name: 'JuliaFormatter check'

# Based off of https://github.com/julia-actions/julia-format/blob/096371fb8d24867760569a7a89359a677595503b/workflows/format_check.yml

on:
  push:
    branches:
      - 'master'
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.0]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@v1
      - name: 'Install JuliaFormatter v0.5.4'
        run: julia -e 'using Pkg; Pkg.add(PackageSpec(name="JuliaFormatter", version="0.5.4"))'
      - name: 'Run `format` function on all files'
        run: julia -e 'using JuliaFormatter; format(".", verbose=true)'
      - name: 'Check that running `format` is a no-op.'
        run: |
          julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files did not meet the formatting guidelines."
              write(stdout, out)
              fix_cmd = """julia -e 'using Pkg; Pkg.activate(tempname()); Pkg.add(PackageSpec(name="JuliaFormatter", version="0.5.4")); using JuliaFormatter; format(".", verbose=true)'"""
              exit(1)
          end'
